### PR TITLE
patch for 5.18+ kernels

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
lmao one line patch

### CODE REVIEW

**Comment by mdhishamsayed** [comment]
please merge this request @choff

**Comment by sickcodes** [comment]
@choff

**Comment by sickcodes** [comment]
Fixed in https://aur.archlinux.org/packages/anbox-modules-dkms

**Comment by choff** [comment]
Thank you very much @Etaash-mathamsetty for this fix! Unfortunately, I didn't see the PR until @sickcodes notified me about it. I think I need to change my Github notification settings again. Thanks also to @sickcodes for the notification and sorry for the delay with the integration.

**Pull request merged**
