### PR TITLE
Create UNINSTALL.sh script and update README.md

### PR DESCRIPTION
**Pull request by SonarBeserk**
This pr creates an uninstall script that is the reverse order of the install script. This allows a clean removal of these modules when uninstalling or reinstalling.

### CODE REVIEW

**Comment by tigercoding56** [comment]
thank you (on my system the modules crash so i had to use pop_os! recovery mode to boot)

**Review by tigercoding56 — CHANGES_REQUESTED** [review]
good!

**Comment by dungdq2002** [comment]
thank you, my computer crashed after installing, this fixed it :D

**Comment by ShindouMihou** [comment]
Recently encountered failure to boot into Pop!_OS after setting this up, been debugging for hours to figure out what was causing, turns out that this anbox-modules was the issue. I'd really appreciate it if the maintainer of this actually pushed this with a warning that failing to uninstall it properly would cause issues like being unable to boot to Pop!_OS.

**Comment by choff** [comment]
Hello @SonarBeserk ,

thank you very much for your changes! I have now merged them. I am very sorry that this took so long. I moved from one place to another and had a lot of things to do.

Thanks again for your contribution.


Best regards,

   Christian

**Comment by SonarBeserk** [comment]
@ShindouMihou I am the author of this pr not the project for clarity but I ask that you please not use such a harsh tone. Everyone has a bit of a different experience installing software like this, in my case things worked fine but I ended up not using the software that required this. So what was required was an uninstall script, without hitting issues directly you wouldn't know to add warnings.

The difference here is really that this is an open source project so we can contribute improvements to documentation and warnings if we wish to. This is currently the best maintained and updated fork of this project ive found, so I appreciate that it exists to improve at all.

**Comment by ShindouMihou** [comment]
> @ShindouMihou I am the author of this pr not for clarity but I ask that you please not use such a harsh tone. Everyone has a bit of a different experience installing software like this, in my case things worked fine but I ended up not using the software that required this. So what was required was an uninstall script, without hitting issues directly you wouldn't know to add warnings.
> 
> The difference here is really that this is an open source project so we can contribute improvements to documentation and warnings if we wish to. This is currently the best maintained and updated fork of this project ive found, so I appreciate that it exists to improve at all.

Oh, I didn't mean to sound rude. I was more just stating my experience over what had happened. 😅 I'm happy that this exists though since it did help out setup waydroid for me, but yeah, had to get rid of waydroid and encountered the boot issue and spent some time wondering why, but this is handy though, don't get me wrong 👀

**Pull request merged**
